---
title: "workout-01: GSW Shot Charts"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

## 2.1 Downloading Data
```{r}
download.file('https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/andre-iguodala.csv', '../data/andre-iguodala.csv')
download.file('https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/draymond-green.csv', '../data/draymond-green.csv')
download.file('https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/kevin-durant.csv', '../data/kevin-durant.csv')
download.file('https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/klay-thompson.csv', '../data/klay-thompson.csv')
download.file('https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/stephen-curry.csv', '../data/stephen-curry.csv')
```

```{r}
curry <- read.csv("../data/stephen-curry.csv", header = T, stringsAsFactors = F)
green <- read.csv("../data/draymond-green.csv", header = T, stringsAsFactors = F)
iguodala <- read.csv("../data/andre-iguodala.csv", header = T, stringsAsFactors = F)
durant <- read.csv("../data/kevin-durant.csv", header = T, stringsAsFactors = F)
thompson <- read.csv("../data/klay-thompson.csv", header = T, stringsAsFactors = F)
```

```{r}
curry %>% mutate(name = "Stephen Curry")
green %>% mutate(name = "Draymond Green")
iguodala %>% mutate(name = "Andre Iguodala")
durant %>% mutate(name = "Kevin Durant")
thompson %>% mutate(name = "Klay Thompson")
```
```{r}
curry[]
```

